# Indentation is super important. If code is not working, First you need to check the indentation

service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters


provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'} # setting up variables, second args is the default value
  region: eu-west-1
  environment: # setting up table variable, so we do not hard code it
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements: # this is an array. Import file usinf ${file():} syntax
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
   

# aws need to use cloudFormation syntax (Capitalized)
# DynamoDB creates Schemaless database using this resources
resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:

  createAuction:
    handler: src/handlers/createAuction.handler
    events:
     # function will be triggered when we make this events requests
      - http:
          method: POST
          path: /auction  
          # when events triggered, handler will be executed
          authorizer: auth # user Auth
  
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http: 
          method: PATCH
          path: /auction/{id}/bid

  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events: 
    #   - schedule: rate(1 minute) 
    # we comment it out now bc it's only for practicing purposes, but deveopling we use this.
      # cron()

custom:
  bundle:
    linting: false     # checking errors off => false
  AuctionsTable:
    name: !Ref AuctionsTable # Ref => returns table name
    arn: !GetAtt AuctionsTable.Arn 

  
  
